name: "Release New Package"

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run:  echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: "Install Dependencies"
        run: | 
          sudo npm install -g yarn 
          sudo yarn add npx
          sudo apt-get install zip
      - name: "Build project, sign and zip"
        env: 
          GRAFANA_API_KEY: ${{secrets.PUBLISHINGKEY}}
        run: |
          yarn install
          yarn run grafana-toolkit plugin:dev
          yarn run grafana-toolkit plugin:sign
          cp -r dist humio
          zip -r humio.zip humio
          md5sum humio.zip
      - name: Upload zip to Github
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: humio.zip
          asset_name: humio.zip
          tag: ${{ env.RELEASE_VERSION }}
          overwrite: true
          body: "Automatic release. See changelog for updates"
