name: "Release New Package"

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install Dependencies"
        run: | 
          sudo npm install -g yarn 
          sudo yarn add npx
          sudo apt-get install zip
      - name: "Build project, sign and zip"
        env: 
          GRAFANA_API_KEY: ${{secrets.PUBLISHINGKEY}}
        run: |
          yarn install
          yarn run grafana-toolkit plugin:dev
          yarn run grafana-toolkit plugin:sign
          cp -r dist humio-datasource
          zip -r humio-datasource.zip humio-datasource
          md5sum humio-datasource.zip
      - name: Upload zip to Github
        uses: svenstaro/upload-release-action@v2
        env:
          TAG_NAME: ${GITHUB_REF#refs/*/}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: humio-datasource.zip
          asset_name: humio-datasource.zip
          tag: $TAG_NAME
          overwrite: true
          body: "Automatic release. See changelog for updates"
